name: bite-lite

services:
  bite-lite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bite-lite
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:4001:4001"
